//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryClientSoap.LibrarySoapProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="LibrarySoapProxy.MyServicePortType")]
    public interface MyServicePortType {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (AddBook_Request) сообщения AddBookRequest не соответствует значению по умолчанию (AddBook).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibraryClientSoap.LibrarySoapProxy.AddBookResponse AddBook(LibraryClientSoap.LibrarySoapProxy.AddBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryClientSoap.LibrarySoapProxy.AddBookResponse> AddBookAsync(LibraryClientSoap.LibrarySoapProxy.AddBookRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (GetBooks_Request) сообщения GetBooksRequest не соответствует значению по умолчанию (GetBooks).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LibraryClientSoap.LibrarySoapProxy.GetBooksResponse GetBooks(LibraryClientSoap.LibrarySoapProxy.GetBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryClientSoap.LibrarySoapProxy.GetBooksResponse> GetBooksAsync(LibraryClientSoap.LibrarySoapProxy.GetBooksRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddBook_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class AddBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public string Author;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=1)]
        public string Title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=2)]
        public int Year;
        
        public AddBookRequest() {
        }
        
        public AddBookRequest(string Author, string Title, int Year) {
            this.Author = Author;
            this.Title = Title;
            this.Year = Year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddBook_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class AddBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public int answer;
        
        public AddBookResponse() {
        }
        
        public AddBookResponse(int answer) {
            this.answer = answer;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/")]
    public partial class SOAP_Book : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string authorField;
        
        private string titleField;
        
        private int yearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
                this.RaisePropertyChanged("Author");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBooks_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class GetBooksRequest {
        
        public GetBooksRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBooks_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class GetBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("answer")]
        public LibraryClientSoap.LibrarySoapProxy.SOAP_Book[] answer;
        
        public GetBooksResponse() {
        }
        
        public GetBooksResponse(LibraryClientSoap.LibrarySoapProxy.SOAP_Book[] answer) {
            this.answer = answer;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyServicePortTypeChannel : LibraryClientSoap.LibrarySoapProxy.MyServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServicePortTypeClient : System.ServiceModel.ClientBase<LibraryClientSoap.LibrarySoapProxy.MyServicePortType>, LibraryClientSoap.LibrarySoapProxy.MyServicePortType {
        
        public MyServicePortTypeClient() {
        }
        
        public MyServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryClientSoap.LibrarySoapProxy.AddBookResponse LibraryClientSoap.LibrarySoapProxy.MyServicePortType.AddBook(LibraryClientSoap.LibrarySoapProxy.AddBookRequest request) {
            return base.Channel.AddBook(request);
        }
        
        public int AddBook(string Author, string Title, int Year) {
            LibraryClientSoap.LibrarySoapProxy.AddBookRequest inValue = new LibraryClientSoap.LibrarySoapProxy.AddBookRequest();
            inValue.Author = Author;
            inValue.Title = Title;
            inValue.Year = Year;
            LibraryClientSoap.LibrarySoapProxy.AddBookResponse retVal = ((LibraryClientSoap.LibrarySoapProxy.MyServicePortType)(this)).AddBook(inValue);
            return retVal.answer;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryClientSoap.LibrarySoapProxy.AddBookResponse> LibraryClientSoap.LibrarySoapProxy.MyServicePortType.AddBookAsync(LibraryClientSoap.LibrarySoapProxy.AddBookRequest request) {
            return base.Channel.AddBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryClientSoap.LibrarySoapProxy.AddBookResponse> AddBookAsync(string Author, string Title, int Year) {
            LibraryClientSoap.LibrarySoapProxy.AddBookRequest inValue = new LibraryClientSoap.LibrarySoapProxy.AddBookRequest();
            inValue.Author = Author;
            inValue.Title = Title;
            inValue.Year = Year;
            return ((LibraryClientSoap.LibrarySoapProxy.MyServicePortType)(this)).AddBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryClientSoap.LibrarySoapProxy.GetBooksResponse LibraryClientSoap.LibrarySoapProxy.MyServicePortType.GetBooks(LibraryClientSoap.LibrarySoapProxy.GetBooksRequest request) {
            return base.Channel.GetBooks(request);
        }
        
        public LibraryClientSoap.LibrarySoapProxy.SOAP_Book[] GetBooks() {
            LibraryClientSoap.LibrarySoapProxy.GetBooksRequest inValue = new LibraryClientSoap.LibrarySoapProxy.GetBooksRequest();
            LibraryClientSoap.LibrarySoapProxy.GetBooksResponse retVal = ((LibraryClientSoap.LibrarySoapProxy.MyServicePortType)(this)).GetBooks(inValue);
            return retVal.answer;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryClientSoap.LibrarySoapProxy.GetBooksResponse> LibraryClientSoap.LibrarySoapProxy.MyServicePortType.GetBooksAsync(LibraryClientSoap.LibrarySoapProxy.GetBooksRequest request) {
            return base.Channel.GetBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryClientSoap.LibrarySoapProxy.GetBooksResponse> GetBooksAsync() {
            LibraryClientSoap.LibrarySoapProxy.GetBooksRequest inValue = new LibraryClientSoap.LibrarySoapProxy.GetBooksRequest();
            return ((LibraryClientSoap.LibrarySoapProxy.MyServicePortType)(this)).GetBooksAsync(inValue);
        }
    }
}
