//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapServiceClient.MyLibraryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="MyLibraryService.MyServicePortType")]
    public interface MyServicePortType {
        
        // CODEGEN: Контракт генерации сообщений с именем упаковщика (GreetUser_Request) сообщения GreetUserRequest не соответствует значению по умолчанию (GreetUser).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        SoapServiceClient.MyLibraryService.GreetUserResponse GreetUser(SoapServiceClient.MyLibraryService.GreetUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapServiceClient.MyLibraryService.GreetUserResponse> GreetUserAsync(SoapServiceClient.MyLibraryService.GreetUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GreetUser_Request", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class GreetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public string user_name;
        
        public GreetUserRequest() {
        }
        
        public GreetUserRequest(string user_name) {
            this.user_name = user_name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GreetUser_Response", WrapperNamespace="http://localhost/", IsWrapped=true)]
    public partial class GreetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/", Order=0)]
        public string answer;
        
        public GreetUserResponse() {
        }
        
        public GreetUserResponse(string answer) {
            this.answer = answer;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyServicePortTypeChannel : SoapServiceClient.MyLibraryService.MyServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServicePortTypeClient : System.ServiceModel.ClientBase<SoapServiceClient.MyLibraryService.MyServicePortType>, SoapServiceClient.MyLibraryService.MyServicePortType {
        
        public MyServicePortTypeClient() {
        }
        
        public MyServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoapServiceClient.MyLibraryService.GreetUserResponse SoapServiceClient.MyLibraryService.MyServicePortType.GreetUser(SoapServiceClient.MyLibraryService.GreetUserRequest request) {
            return base.Channel.GreetUser(request);
        }
        
        public string GreetUser(string user_name) {
            SoapServiceClient.MyLibraryService.GreetUserRequest inValue = new SoapServiceClient.MyLibraryService.GreetUserRequest();
            inValue.user_name = user_name;
            SoapServiceClient.MyLibraryService.GreetUserResponse retVal = ((SoapServiceClient.MyLibraryService.MyServicePortType)(this)).GreetUser(inValue);
            return retVal.answer;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapServiceClient.MyLibraryService.GreetUserResponse> SoapServiceClient.MyLibraryService.MyServicePortType.GreetUserAsync(SoapServiceClient.MyLibraryService.GreetUserRequest request) {
            return base.Channel.GreetUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapServiceClient.MyLibraryService.GreetUserResponse> GreetUserAsync(string user_name) {
            SoapServiceClient.MyLibraryService.GreetUserRequest inValue = new SoapServiceClient.MyLibraryService.GreetUserRequest();
            inValue.user_name = user_name;
            return ((SoapServiceClient.MyLibraryService.MyServicePortType)(this)).GreetUserAsync(inValue);
        }
    }
}
